apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: {{ include "opentelemetry-templates.fullname" . }}-collectors
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: opentelemetry-collector
  endpoints:
  - port: 8888
    scheme: http
    path: "/metrics"
    interval: 10s