# If disabled, no resources in the chart will be created
enabled: true

# Preview, these values are provided by the ArgoCD Pull Request Generator and should not be populated unless testing
preview:
  pr: 17
  host: pr17-chart.preview.mozilla.cloud

# Defines the backend services to create, backend policies, and healthchecks.
backends:
    # Definitions for the Kubernetes service.
  - service:
      # If disabled, a new Kubernetes will not be created.
      #create: true

      port: 8080

      # Name of the port to create. Default is "http".
      #portName: http

      # Protocol used for service. Default is TCP. More information found
      # here:
      # https://kubernetes.io/docs/reference/networking/service-protocols/
      #protocol: TCP

      # Port name/number of pods the service should target. Default is "http".
      targetPort: http

      # Annotations to use for this service.
      #annotations: {}

      # Labels to use for the service.
      #labels: {}

      # Selector labels the service should use to match against pods.
      #selectorLabels: {}

    # Set a name for the backend to use for all related components.
    #name:

    # Backend policy to apply to this specific backend service. Overrides the
    # defaults from .Values.backendPolicy
    #backendPolicy: {}

    # Health check configurations for the load balancer to perform against the
    # backend service.
    #
    # By default, Kubernetes services will perform health checks against pods
    # using readinessProbes and livenessProbes. This section allows users to
    # specify health check configurations at the load balancer level, which
    # provides more fine-grained control over how health checks are performed.
    healthCheck:
      # The request path to use for the health check. Default is
      # "/__lbheartbeat__".
      path: /__lbheartbeat__

      # The protocol to use for health checks. Options are "HTTP" or "TCP".
      # Default is "HTTP".
      protocol: HTTP

      # The port to use for the health check, if different from the service
      # port. This port must be specified as a number, not a named port.
      #port:

      # The interval (in seconds) in which the endpoint is probed for a health
      # check.
      #checkIntervalSec:

      # The timeout (in seconds) for the health check probe.
      #timeoutSec:

      # Number of sequential connection attempts that must succeed for a backend
      # to be considered healthy.
      #healthyThreshold:

      # Number of sequential connection attempts that must succeed for a backend
      # to be considered unhealthy.
      #unhealthyThreshold:

    # Labels for the backend resources. Overridden for services by
    # "service.labels".
    #labels: {}

# Defines specific parameters of the frontend of the Google Cloud load
# balancer. This policy is similar to a FrontendConfig for an Ingress resource.
gatewayPolicy:
  # SSL policy to use. This configures a set of TLS versions and ciphers that
  # the load balancer uses to terminate HTTPS traffic from clients.
  sslPolicy: mozilla-intermediate

# Defines how HTTP and HTTPS requests received by a Gateway are directed to
# Services.
httpRoute:
  # If disabled, HTTPRoute resources will not be created in the K8s namespace.
  enabled: true

  httpRoutes:
    - name: mozcloud-gateway
      # Hostnames to match against. Hostnames are matched before any other
      # matches (path, headers) occur.
      hostnames:
        - chart.example.local

      # If enabled, create an HTTP-to-HTTPS redirect. This is enabled by
      # default.
      #httpToHttpsRedirect: true

      rules:
          # A list of the backend services to receive traffic.
        - backendRefs:
              # The name of the backend service
            - name: mozcloud-gateway
              port: 8080