{{- define "common.externalSecret" -}}
{{- if .externalSecrets }}
{{- $external_secrets := include "common.config.externalSecrets" . | fromYaml }}
{{- range $external_secret := $external_secrets.externalSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $external_secret.name }}
  labels:
    {{- $external_secret.labels | toYaml | nindent 4 }}
  {{- $params := dict "type" "externalSecret" }}
  {{- $annotations := include "common.annotations.argo" $params | fromYaml }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: {{ $external_secret.refreshInterval }}
  secretStoreRef:
    kind: SecretStore
    name: secret-store
  target:
    name: {{ $external_secret.target }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ $external_secret.gsm.secret }}
        metadataPolicy: None
        version: {{ $external_secret.gsm.version | quote }}
{{- end }}
{{- end }}
{{- end -}}
