{{- define "common.serviceAccount" -}}
{{- if .serviceAccounts }}
{{- $serviceAccounts := include "common.config.serviceAccounts" . | fromYaml }}
{{- range $serviceAccount := $serviceAccounts.serviceAccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccount.name }}
  labels:
    {{- $serviceAccount.labels | toYaml | nindent 4 }}
  {{- $params := dict "type" "serviceAccount" }}
  {{- $annotations := include "common.annotations.argo" $params | fromYaml }}
  {{- if or $annotations $serviceAccounts.gcpServiceAccount }}
  annotations:
    {{- if $serviceAccount.gcpServiceAccount }}
    iam.gke.io/gcp-service-account: {{ $serviceAccount.gcpServiceAccount }}
    {{- end }}
    {{- if $annotations }}
    {{- $annotations | toYaml | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end -}}
