{{- define "common.serviceAccount" -}}
{{- if .serviceAccounts }}
{{- $service_accounts := include "common.config.serviceAccounts" . | fromYaml }}
{{- range $service_account := $service_accounts.serviceAccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $service_account.name }}
  labels:
    {{- $service_account.labels | toYaml | nindent 4 }}
  {{- if or $service_account.gcpServiceAccount $service_account.annotations }}
  annotations:
    {{- if $service_account.gcpServiceAccount }}
    iam.gke.io/gcp-service-account: {{ $service_account.gcpServiceAccount }}
    {{- end }}
    {{- $annotation_params := dict "annotations" (default (dict) $service_account.annotations) "context" ($ | deepCopy) "type" "serviceAccount" }}
    {{- $annotations := include "common.annotations" $annotation_params | fromYaml }}
    {{- if $annotations }}
    {{- $annotations | toYaml | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end -}}
