{{- $chartMetadata := dict "Chart" .Chart "Release" .Release }}
{{- $context := deepCopy . }}
{{- $labelParams := mergeOverwrite $chartMetadata (include "mozcloud.labelParams" . | fromYaml) }}
{{- $params := dict "configMaps" .Values.configMaps "context" $context }}
{{- /* Transform configMap names and data for preview environments, if enabled */}}
{{- $configMaps := include "mozcloud.configMap.formatter.preview" $params | fromYaml }}
{{- $tplEnabled := ((.Values.experimental).tplEnabled).configMaps }}
{{- if $configMaps }}
{{- $_ := set $context "component_code" "configmap" -}}
{{- range $name, $config := $configMaps }}
{{- if gt (keys $config.data | len) 0 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}
  labels:
    {{- $params := dict "context" (mergeOverwrite (deepCopy $context) $labelParams) }}
    {{- $labels := include "mozcloud.labels" $params | fromYaml }}
    {{- $labels.labels | toYaml | nindent 4 }}
  {{- $params = dict "type" "configMap" }}
  {{- $annotations := include "mozcloud.annotations.argo" $params | fromYaml }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | toYaml | nindent 4 }}
  {{- end }}
data:
  {{- $enabled := or $tplEnabled $config.tplEnabled }}
  {{- range $key, $value := $config.data }}
  {{- $field := printf "configMaps.%s.data.%s" $name $key }}
  {{- $params = dict "value" $value "context" $context "enabled" $enabled "field" $field }}
  {{ $key }}: {{ include "mozcloud.renderTpl" $params | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
