{{- define "mozcloud-deployment-lib.deployment" -}}
{{- if .deployments }}
{{- $deployments := include "mozcloud-deployment-lib.config.deployments" . | fromYaml }}
{{- range $deployment := $deployments.deployments }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deployment.name }}
  labels:
    {{- $deployment.labels | toYaml | nindent 4 }}
spec:
  selector:
    {{- include "mozcloud-workload-core-lib.selectorLabels" $ | nindent 4 }}
  template:
    metadata:
      labels:
        {{- $deployment.labels | toYaml | nindent 8 }}
    spec:
      containers:
        {{- range $container := $deployment.containers }}
        - name: {{ $container.name }}
          image: {{ printf "%s:%s" $container.image.repo $container.image.tag }}
          imagePullPolicy: IfNotPresent
          {{- if $container.envFrom }}
          envFrom:
            {{- $container.envFrom | toYaml | nindent 12 }}
          {{- end }}
          ports:
            {{- $container.ports | toYaml | nindent 12 }}
          {{- if $container.livenessProbe }}
          livenessProbe:
            {{- $container.livenessProbe | toYaml | nindent 12 }}
            failureThreshold: 5
            initialDelaySeconds: 10
            periodSecondS: 6
            timeoutSeconds: 5
          {{- end }}
          {{- if $container.readinessProbe }}
          redinessProbe:
            {{- $container.readinessProbe | toYaml | nindent 12 }}
            initialDelaySeconds: 10
            periodSecondS: 6
            timeoutSeconds: 5
          {{- end }}
          resources:
            {{- include "mozcloud-workload-core-lib.pod.container.resources" (default (dict) $container.resources) | nindent 12 }}
          securityContext:
            {{- include "mozcloud-workload-core-lib.pod.container.securityContext" (default (dict) $container.securityContext) | nindent 12 }}
        {{- end }}
{{- end }}
{{- end }}
{{- end -}}
