{{- $chartMetadata := dict "Chart" .Chart "Release" .Release }}
{{- $context := deepCopy . }}
{{- $labelParams := mergeOverwrite $chartMetadata (include "mozcloud.labelParams" . | fromYaml) }}
{{- /* Format workloads, removing default container and merging user-defined values with defaults */}}
{{- $previewConfig := mergeOverwrite (default dict .Values.global.preview) (default dict .Values.preview) }}
{{- $formatterParams := dict "workloads" (.Values.workloads | deepCopy) "preview" $previewConfig }}
{{- $workloads := include "mozcloud.formatter.workloads" $formatterParams | fromYaml -}}

{{- range $workloadName, $workloadConfig := $workloads }}
{{- if eq (default "deployment" $workloadConfig.type) "deployment" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $workloadName }}
  labels:
    {{- $component := dict "component_code" $workloadConfig.component }}
    {{- $params := dict "context" (mergeOverwrite (deepCopy $context) (mergeOverwrite (deepCopy $labelParams) $component)) }}
    {{- $labels := include "mozcloud.labels" $params | fromYaml }}
    {{- $labels.labels | toYaml | nindent 4 }}
  {{- $params = dict "annotations" (default dict $workloadConfig.annotations) "context" $context "type" "deployment" }}
  {{- $annotations := include "mozcloud.annotations" $params | fromYaml }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- $labels.selectorLabels | toYaml | nindent 6 }}
  strategy:
    type: {{ default "RollingUpdate" $workloadConfig.strategy }}
  {{- /*
  The template below can be found in templates/workload/_workloadTemplate.yaml
  */}}
  {{- $params = dict "config" $workloadConfig "context" $context "name" $workloadName }}
  {{- include "mozcloud.workload.workloadTemplate" $params | nindent 2 }}
{{- $nginxEnabled := and (dig "nginx" "enabled" "true" $workloadConfig) $workloadConfig.hosts }}
{{- if and $nginxEnabled (not $workloadConfig.nginx.configMap) }}
---
{{- include "mozcloud.workload.nginxConfigMap" (dict
  "labels" $labels
  "name" $workloadName
) }}
{{- end }}
{{- end }}
{{- end }}
