{{- define "mozcloud-workload-core-lib.externalSecret" -}}
{{- if .externalSecrets }}
{{- $external_secrets := include "mozcloud-workload-core-lib.config.externalSecrets" . | fromYaml }}
{{- range $external_secret := $external_secrets.externalSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $external_secret.name }}
  labels:
    {{- $external_secret.labels | toYaml | nindent 4 }}
  {{- if $external_secret.annotations }}
  annotations:
    {{- $external_secret.annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: {{ $external_secret.refreshInterval }}
  secretStoreRef:
    kind: SecretStore
    name: secret-store
  target:
    name: {{ $external_secret.target }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ $external_secret.gsm.secret }}
        version: {{ $external_secret.gsm.version | quote }}
{{- end }}
{{- end }}
{{- end -}}
