apiVersion: v2
name: mozcloud-workload
description: Opinionated application chart used to deploy MozCloud workloads and
  supporting resources
version: 0.3.9
type: application
dependencies:
  - name: mozcloud-gateway-lib
    version: 0.4.21
    repository: file://../../mozcloud-gateway/library
  - name: mozcloud-ingress-lib
    version: 0.4.16
    repository: file://../../mozcloud-ingress/library
  - name: mozcloud-job-lib
    version: 0.5.7
    repository: file://../../mozcloud-job/library
  - name: mozcloud-labels-lib
    version: 0.3.12
    repository: file://../../mozcloud-labels/library
  - name: mozcloud-workload-stateless-lib
    version: 0.4.35
    repository: file://../../mozcloud-workload-stateless/library
  - name: mozcloud-workload-core-lib
    version: 0.6.17
    repository: file://../../mozcloud-workload-core/library
