{{/*
Ingresses
*/}}
{{- /*
This function creates the value structure needed for ingress, backendConfig,
managedCertificate, and service templates in the mozcloud-ingress-lib library
chart.

Params:

globals (dict): (required) Global values from .Values.global.mozcloud.
workloads (dict): (required) All of the workloads created using this chart. This
                  is populated below this function via the workload formatter
                  function.
*/}}
{{- define "mozcloud.config.ingresses" -}}
{{- $globals := .globals }}
{{- $workloads := .workloads }}
ingresses:
  {{- range $workloadName, $workloadConfig := $workloads }}
  {{- range $hostName, $hostConfig := default (dict) $workloadConfig.hosts }}
  {{- if eq $hostConfig.type "external" }}
  {{ $hostName }}:
    component: {{ $workloadConfig.component }}
    hosts:
      - domains:
          {{- range $domain := $hostConfig.domains }}
          - {{ $domain | quote }}
          {{- end }}
        paths:
          - path: /
            pathType: Prefix
            backend:
              config:
                name: {{ $workloadName }}
                {{- if (($hostConfig.options).iap).enabled }}
                iap:
                  enabled: {{ $hostConfig.options.iap.enabled }}
                {{- end }}
                {{- if ($hostConfig.options).logSampleRate }}
                logging:
                  {{- $sampleRate := $hostConfig.options.logSampleRate | float64 }}
                  sampleRate: {{ divf $sampleRate 100 }}
                {{- end }}
                {{- if ($hostConfig.options).timeoutSec }}
                  timeoutSec: {{ $hostConfig.options.timeoutSec }}
                {{- end }}
              service:
                name: {{ $workloadName }}
                port: 8080
                protocol: TCP
                targetPort: http
        tls:
          {{- $type := ($hostConfig.tls.type) }}
          {{- if or (not $type) (eq $type "certmap") }}
            {{- $type = "ManagedCertificate" }}
          {{- end }}
          type: {{ $type }}
          {{- if and (hasKey $hostConfig.tls "create") ($hostConfig.tls.create) }}
          createCertificates: true
          {{- if eq $type "ManagedCertificate" }}
          multipleHosts: false
          {{- end }}
          {{- end }}
          {{- if eq $type "pre-shared" }}
          preSharedCerts: {{ join "," (uniq $hostConfig.tls.certs | sortAlpha) | quote }}
          {{- end }}
    {{- if $hostConfig.addresses }}
    staticIpName: {{ $hostConfig.addresses | first }}
    {{- else }}
    staticIpName: {{ $globals.app_code }}-{{ $globals.env_code }}-ip-v4
    {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end -}}

{{- /* We do not use ingress resources for preview environments */}}
{{- if and .Values.enabled (not (include "mozcloud.preview.enabled" .)) }}
  {{- $chartMetadata := dict "Chart" .Chart "Release" .Release }}
  {{- $context := deepCopy . }}
  {{- $labelParams := mergeOverwrite $chartMetadata (include "mozcloud.labelParams" . | fromYaml) }}
  {{- /* Call a helper function that merges user data with defaults */}}
  {{- $previewConfig := mergeOverwrite (default dict .Values.global.preview) (default dict .Values.preview) }}
  {{- /* Get only workloads where "api: ingress" is set */}}
  {{- $formatterParams := dict "api" "ingress" "workloads" (.Values.workloads | deepCopy) "preview" $previewConfig }}
  {{- $workloads := include "mozcloud.formatter.workloads" $formatterParams | fromYaml -}}

  {{- /*
  Only include Ingress and related resources if we have Ingress hosts defined
  */}}
  {{- $hosts := list }}
  {{- range $workloadName, $workloadConfig := $workloads }}
    {{- range $hostName, $hostConfig := $workloadConfig.hosts }}
      {{- $hosts = append $hosts $hostName }}
    {{- end }}
  {{- end }}
  {{- if gt (len $hosts) 0 }}
    {{- /*
    Ingresses and related resources
    */}}
    {{- $params := mergeOverwrite $context (dict "globals" .Values.global.mozcloud "workloads" $workloads) }}
    {{- $ingresses := (include "mozcloud.config.ingresses" $params | fromYaml).ingresses }}
    {{- range $ingressName, $ingressConfig := $ingresses }}
      {{- $_ := set $labelParams "component_code" $ingressConfig.component }}
      {{- $_ = set $params "ingressConfig" (dict $ingressName (omit $ingressConfig "component")) }}
{{ include "mozcloud-ingress-lib.ingress" (mergeOverwrite $params $labelParams) }}
{{ include "mozcloud-ingress-lib.backendConfig" (mergeOverwrite $params $labelParams) }}
{{ include "mozcloud-ingress-lib.managedCertificate" (mergeOverwrite $params $labelParams) }}
{{ include "mozcloud-ingress-lib.service" (mergeOverwrite $params $labelParams) }}
    {{- end }}
  {{- end }}
{{- end -}}
