apiVersion: v2
name: mozcloud
description: Opinionated application chart used to deploy MozCloud Kubernetes 
  resources supporting resources
version: 1.3.0
type: application
dependencies:
  - name: mozcloud-gateway-lib
    version: 1.0.0
    repository: file://../../mozcloud-gateway/library
  - name: mozcloud-ingress-lib
    version: 1.1.0
    repository: file://../../mozcloud-ingress/library
  - name: mozcloud-labels-lib
    version: 1.0.0
    repository: file://../../mozcloud-labels/library
