{{- if .Values.collectors.gateway.statsdService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mozcloud-opentelemetry.name" . }}-gateway-statsd
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.collectors.gateway.statsdService.sessionAffinityTimeoutSeconds }}
  selector:
    app.kubernetes.io/name: {{ include "mozcloud-opentelemetry.name" . }}-gateway-collector
  ports:
  - name: statsd
    port: 8125
    targetPort: 8125
    protocol: UDP
{{- end }}
