apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: {{ include "mozcloud-opentelemetry.name" . }}-gateway
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.serviceAccount.create }}
  serviceAccount: {{ .Values.serviceAccount.name }}
  {{- end }}
  mode: deployment
  terminationGracePeriodSeconds: 600
  hostNetwork: false
  {{- with .Values.collectors.gateway.securityContext }}
  securityContext: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.collectors.gateway.autoscaler }}
  autoscaler: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.collectors.gateway.resources }}
  resources: {{ toYaml . | nindent 4 }}
  {{- end }}
  env:
  - name: POD_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
  - name: POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP

  ports:
  - name: otlp-collecotrs
    port: {{ .Values.collectors.gateway.endpoints.otlp.collectorMetricsPort }}
    targetPort: {{ .Values.collectors.gateway.endpoints.otlp.collectorMetricsPort }}

  config:
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}

      otlp/collectors:
        protocols:
          http:
            endpoint: "0.0.0.0:{{ .Values.collectors.gateway.endpoints.otlp.collectorMetricsPort }}"

      statsd:
        endpoint: ${env:POD_IP}:8125
        aggregation_interval: 30s
        enable_metric_type: true
        enable_simple_tags: true
        is_monotonic_counter: true

    processors:
      # The relative ordering of statements between ReplicaSet & Deployment and Job & CronJob are important.
      # The ordering of these controllers is decided based on the k8s controller documentation available at
      # https://kubernetes.io/docs/concepts/workloads/controllers.
      # The relative ordering of the other controllers in this list is inconsequential since they directly
      # create pods.
      transform/aco-gke:
        metric_statements:
        - context: datapoint
          statements:
          - set(attributes["top_level_controller_type"], "ReplicaSet") where resource.attributes["k8s.replicaset.name"] != nil
          - set(attributes["top_level_controller_name"], resource.attributes["k8s.replicaset.name"]) where resource.attributes["k8s.replicaset.name"] != nil
          - set(attributes["top_level_controller_type"], "Deployment") where resource.attributes["k8s.deployment.name"] != nil
          - set(attributes["top_level_controller_name"], resource.attributes["k8s.deployment.name"]) where resource.attributes["k8s.deployment.name"] != nil
          - set(attributes["top_level_controller_type"], "DaemonSet") where resource.attributes["k8s.daemonset.name"] != nil
          - set(attributes["top_level_controller_name"], resource.attributes["k8s.daemonset.name"]) where resource.attributes["k8s.daemonset.name"] != nil
          - set(attributes["top_level_controller_type"], "StatefulSet") where resource.attributes["k8s.statefulset.name"] != nil
          - set(attributes["top_level_controller_name"], resource.attributes["k8s.statefulset.name"]) where resource.attributes["k8s.statefulset.name"] != nil
          - set(attributes["top_level_controller_type"], "Job") where resource.attributes["k8s.job.name"] != nil
          - set(attributes["top_level_controller_name"], resource.attributes["k8s.job.name"]) where resource.attributes["k8s.job.name"] != nil
          - set(attributes["top_level_controller_type"], "CronJob") where resource.attributes["k8s.cronjob.name"] != nil
          - set(attributes["top_level_controller_name"], resource.attributes["k8s.cronjob.name"]) where resource.attributes["k8s.cronjob.name"] != nil
          # podmonitoring uses 'pod' label, so we'll standardize on that
          - set(attributes["pod"], resource.attributes["k8s.pod.name"]) where resource.attributes["k8s.pod.name"] != nil

      resource/gcp_project_id:
        attributes:
        - key: gcp.project_id
          value: {{ $.Values.project_id }}
          action: insert

      memory_limiter:
        check_interval: 1s
        limit_percentage: 65
        spike_limit_percentage: 20

      tail_sampling:
        policies:
          - name: error_traces
            type: status_code
            status_code:
              status_codes: [ERROR]
          - name: default_probabilistic
            type: probabilistic
            probabilistic:
              sampling_percentage: 1.0

      resourcedetection:
        detectors: [env, gcp]
        timeout: 10s
        override: false

    exporters:
      debug:
        verbosity: detailed

      googlemanagedprometheus:
        metric:
          # GMP exporter automatically adds the following labels from the listed attributes
          #   project_id: auto-detected by Application Default Credentials, gcp.project.id, or project in exporter config
          #   location: location, cloud.availability_zone, cloud.region
          #   cluster: cluster, k8s.cluster_name
          #   namespace: namespace, k8s.namespace_name
          #   job: service.name + service.namespace
          #   instance: service.instance.id
          # Code below adds additional labels from attributes
          resource_filters:
          - prefix: "cloud"
          - prefix: "k8s"
          - prefix: "faas"
          - regex: "container.id"
          - regex: "process.pid"
          - regex: "host.name"
          - regex: "host.id"
          # MozCloud operational labels
          - regex: "artifact_version"
          {{- $mozcloud_annotation_params := .Values.global.mozcloud }}
          {{- $mozcloud_annotations := include "mozcloud-labels-lib.annotations.otel.fields" $mozcloud_annotation_params | fromYaml }}
          {{- range $name, $value := $mozcloud_annotations }}
          - regex: {{ $name | quote }}
          {{- end }}
        sending_queue:
          batch: {}

      otlphttp:
        encoding: json
        endpoint: https://telemetry.googleapis.com
        auth:
          authenticator: googleclientauth
        sending_queue:
          batch:
            sizer: items
            min_size: 200
            max_size: 200
            flush_timeout: 5s

    extensions:
      health_check:
        endpoint: ${env:POD_IP}:13133
      googleclientauth: {}

    service:
      extensions:
      - health_check
      - googleclientauth
      pipelines:
        metrics:
          receivers:
          - otlp
          - statsd
          processors:
          - memory_limiter
          - resource/gcp_project_id
          exporters:
          - otlphttp
        metrics/collectors:
          receivers:
          - otlp/collectors
          processors:
          - memory_limiter
          - resourcedetection
          - resource/gcp_project_id
          exporters:
          - otlphttp
        traces:
          receivers:
          - otlp
          processors:
          - memory_limiter
          - resource/gcp_project_id
          - tail_sampling
          exporters:
          - otlphttp
      telemetry:
        logs:
          encoding: json
        resource:
          k8s.deployment.name: {{ include "mozcloud-opentelemetry.name" . }}-gateway-collector
          k8s.pod.name: ${POD_NAME}
          namespace: ${POD_NAMESPACE}
        metrics:
          readers:
            - periodic:
                exporter:
                  otlp:
                    protocol: http/protobuf
                    endpoint: http://${env:POD_IP}:14318
