---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: {{ include "mozcloud-opentelemetry.name" . }}-instrumentation
  namespace: {{ .Release.Namespace }}
spec:
  exporter:
    # instrumentation will automatically inject OTEL_NODE_IP and OTEL_POD_IP environment variables
    endpoint: http://$(OTEL_NODE_IP):4318
  propagators:
    - tracecontext
    - baggage
  python:
    env:
      # https://opentelemetry.io/docs/zero-code/python/configuration/#disabling-specific-instrumentations
      #     - name: OTEL_PYTHON_DISABLED_INSTRUMENTATIONS
      #       value:
      #         <comma-separated list of package names to exclude from instrumentation>
      - name: OTEL_PYTHON_DISABLED_INSTRUMENTATIONS
        value: "system_metrics"
