---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    type: "opentelemetry"
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: restricted