{{- if .Values.serviceAccount.create | default false }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    {{- include "mozcloud-opentelemetry.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.name }}@{{ .Values.project_id }}.iam.gserviceaccount.com
{{- end }}
