apiVersion: v2
name: mozcloud-kit
description: mozcloud opinionated bundle of helm charts
version: 0.3.0
type: application
dependencies:
  - name: mozcloud-labels-lib
    version: 0.3.0
    repository: oci://us-west1-docker.pkg.dev/moz-fx-platform-artifacts/mozcloud-charts

  - name: mozcloud-workload-stateless
    version: 0.2.0
    repository: oci://us-west1-docker.pkg.dev/moz-fx-platform-artifacts/mozcloud-charts
