{{- if .Values.enabled }}
{{- $chartMetadata := dict "Chart" .Chart "Release" .Release }}
{{- $context := deepCopy . }}
{{- $_ := set $context "component_code" "externalsecret" -}}
{{- $externalSecrets := default dict .Values.externalSecrets }}
{{- $globals := .Values.global.mozcloud }}
{{- $labelParams := mergeOverwrite $chartMetadata (include "mozcloud.labelParams" . | fromYaml) }}
{{- $prefix := include "mozcloud.preview.prefix" . -}}
{{- /* The first secret is the default tenant secret that maps to <env>-gke-app-secrets in GSM */}}
{{- $defaultSecretName := printf "%s%s-secrets" $prefix $globals.chart }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $defaultSecretName }}
  labels:
    {{- $params := dict "context" (mergeOverwrite (deepCopy $context) $labelParams) }}
    {{- $labels := include "common.labels" $params | fromYaml }}
    {{- $labels.labels | toYaml | nindent 4 }}
  {{- $params := dict "type" "externalSecret" }}
  {{- $annotations := include "common.annotations.argo" $params | fromYaml }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: SecretStore
    name: secret-store
  target:
    name: {{ $defaultSecretName }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ $globals.env_code }}-gke-app-secrets
        metadataPolicy: None
        version: latest
{{- range $name, $config := $externalSecrets }}
{{- $name = printf "%s%s" $prefix $name }}
{{- /* These are all user-defined secrets */}}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $name }}
  labels:
    {{- $labels.labels | toYaml | nindent 4 }}
  {{- $params := dict "type" "externalSecret" }}
  {{- $annotations := include "common.annotations.argo" $params | fromYaml }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: {{ default "5m" $config.refreshInterval }}
  secretStoreRef:
    kind: SecretStore
    name: secret-store
  target:
    name: {{ $name }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ $config.gsmSecretName }}
        metadataPolicy: None
        version: {{ default "latest" $config.version | quote }}
{{- end }}
{{- end }}
