{{- if and .Values.enabled (.Values.httpRoute).enabled }}
{{- $params := dict "backendConfig" (dict "backends" .Values.backends) "nameOverride" (include "mozcloud-gateway.name" .) "Chart" .Chart "Release" .Release }}
{{- $label_params := include "mozcloud-gateway.labelParams" . | fromYaml }}
{{- include "mozcloud-gateway-lib.service" (mergeOverwrite $params $label_params) }}
{{- end }}
