{{- define "mozcloud-ingress-lib.ingress" -}}
{{- $name_override := default "" .nameOverride }}
{{- $backend_defaults := include "mozcloud-ingress-lib.defaults.backendConfig" . | fromYaml }}
{{- $ingresses := include "mozcloud-ingress-lib.config.ingresses" . | fromYaml }}
{{- $frontend_config := include "mozcloud-ingress-lib.config.frontend" . | fromYaml }}
{{- $managed_certificates := include "mozcloud-ingress-lib.config.managedCertificates" . | fromYamlArray }}
{{- range $ingress := $ingresses.ingresses }}
{{- $params := (dict "ingressConfig" $ingress) }}
{{- if $name_override }}
{{- $_ := set $params "nameOverride" $name_override }}
{{- end }}
{{- $ingress_name := include "mozcloud-ingress-lib.config.name" $params }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $ingress_name }}
  labels:
    {{- $label_params := dict "labels" (default (dict) $ingress.labels) }}
    {{- $labels := include "mozcloud-ingress-lib.labels" (mergeOverwrite $ $label_params) | fromYaml }}
    {{- $labels | toYaml | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: {{ default "mozcloud-ingress-dev-ip-v4" $ingress.staticIpName }}
    {{- if gt (len $managed_certificates) 0 }}
    {{- $certs := list }}
    {{- range $managed_certificate := $managed_certificates }}
    {{- if and (eq $managed_certificate.ingressName $ingress_name) $managed_certificate.createCertificate }}
    {{- $certs = append $certs $managed_certificate.name }}
    {{- end }}
    {{- end }}
    {{- if gt (len $certs) 0 }}
    networking.gke.io/managed-certificates: {{ join "," (uniq $certs | sortAlpha) }}
    {{- end }}
    {{- end }}
    {{- if (index $ingresses "preSharedCerts" $ingress_name) }}
    ingress.gcp.kubernetes.io/pre-shared-cert: {{ index $ingresses "preSharedCerts" $ingress_name }}
    {{- end }}
    networking.gke.io/v1beta1.FrontendConfig: {{ $frontend_config.name }}
spec:
  {{- if and (eq (len $ingress.hosts) 1) (eq (len (first $ingress.hosts).paths) 1) }}
  {{- range $host := $ingress.hosts }}
  {{- range $path := $host.paths }}
  {{- $backend := mergeOverwrite $backend_defaults (default (dict) $path.backend.config) }}
  {{- $backend_service := $path.backend.service }}
  defaultBackend:
    service:
      {{- $params := dict "backendConfig" $backend "backendService" $backend_service "ingressConfig" $ingress }}
      {{- if $name_override }}
      {{- $_ := set $params "nameOverride" $name_override }}
      {{- end }}
      name: {{ include "mozcloud-ingress-lib.config.backend.name" $params }}
      port:
        number: {{ $backend_service.port }}
  {{- end }}
  {{- end }}
  {{- else }}
    rules:
      {{- range $host := $ingress.hosts }}
      {{- range $domain := $host.domains }}
      - host: {{ $domain }}
        http:
          paths:
            {{- range $path := $host.paths }}
            {{- $backend := mergeOverwrite $backend_defaults (default (dict) $path.backend.config) }}
            {{- $backend_service := $path.backend.service }}
            - path: {{ $path.path }}
              pathType: {{ $path.pathType }}
              backend:
                service:
                  {{- $params := dict "backendConfig" $backend "backendService" $backend_service "ingressConfig" }}
                  {{- if $name_override }}
                  {{- $_ := set $params "nameOverride" $name_override }}
                  {{- end }}
                  name: {{ include "mozcloud-ingress-lib.config.service.name" $params }}
                  port:
                    number: {{ $backend_service.port }}
            {{- end }}
      {{- end }}
      {{- end }}
  {{- end }}
{{- end }}
{{- end -}}
