{{- define "mozcloud-ingress-lib.managedCertificates" -}}
{{- $managedCertificates := include "mozcloud-ingress-lib.config.managedCertificates" . | fromYaml }}
{{- range $managedCertificate := $managedCertificates }}
{{- range $name, $domains := $managedCertificate }}
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ $name }}
  labels:
    {{- include "mozcloud-ingress-lib.labels" . | nindent 4 }}
spec:
  domains:
    {{- range $domain := $domains }}
    - {{ $domain }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
