{{- define "mozcloud-ingress.service" -}}
{{- $services := include "mozcloud-ingress.config.services" . | fromYaml }}
{{- range $service := $services }}
{{- include "mozcloud-service.service" $service }}
{{- end }}
{{- end }}
