{{- if .Values.enabled }}
{{- $params := dict "ingressConfig" .Values.ingresses "defaults" .Values.backendConfig "nameOverride" (include "mozcloud-ingress.name" .) "Chart" .Chart "Release" .Release }}
{{- $label_params := include "mozcloud-ingress.labelParams" .  | fromYaml }}
{{- include "mozcloud-ingress-lib.backendConfig" (mergeOverwrite $params $label_params) }}
{{- end }}
