{{- if .Values.enabled }}
{{- $params := dict "frontendConfig" .Values.frontendConfig "nameOverride" (include "mozcloud-ingress.name" .) "Chart" .Chart "Release" .Release }}
{{- $label_params := include "mozcloud-ingress.labelParams" .  | fromYaml }}
{{- include "mozcloud-ingress-lib.frontendConfig" (mergeOverwrite $params $label_params) }}
{{- end }}
