{{- if .Values.enabled }}
{{- $params := dict "frontendConfig" .Values.frontendConfig "Chart" .Chart "Release" .Release }}
{{- if .Values.nameOverride }}
  {{- $_ := set $params "nameOverride" .Values.nameOverride }}
{{- end }}
{{- $label_params := include "mozcloud-ingress.labelParams" .  | fromYaml }}
{{- include "mozcloud-ingress-lib.frontendConfig" (mergeOverwrite $params $label_params) }}
{{- end }}
