{{- if .Values.enabled }}
{{- $params := dict "frontendConfig" .Values.frontendConfig "nameOverride" (include "mozcloud-ingress.name" .) "Chart" .Chart "Release" .Release }}
{{- include "mozcloud-ingress-lib.frontendConfig" $params }}
{{- end }}
