{{- if .Values.enabled }}
{{- $params := dict "defaults" .Values.backendConfig "ingressConfig" .Values.ingresses "nameOverride" (include "mozcloud-ingress.name" .) "Chart" .Chart "Release" .Release }}
{{- $label_params := include "mozcloud-ingress.labelParams" .  | fromYaml }}
{{- include "mozcloud-ingress-lib.ingress" (mergeOverwrite $params $label_params) }}
{{- end }}
