{{- if .Values.enabled }}
{{- $params := dict "ingressConfig" .Values.ingresses "nameOverride" (include "mozcloud-ingress.name" .) "Chart" .Chart "Release" .Release }}
{{- $label_params := include "mozcloud-ingress.labelParams" . | fromYaml }}
{{- include "mozcloud-ingress-lib.service" (mergeOverwrite $params $label_params) }}
{{- end }}
