{{- if .Values.enabled }}
{{- $params := dict "ingresses" .Values.ingresses "nameOverride" (include "mozcloud-ingress.name" .) "Chart" .Chart "Release" .Release }}
{{- include "mozcloud-ingress-lib.service" $params }}
{{- end }}
