{{- if .Values.enabled }}
{{- $chartMetadata := dict "Chart" .Chart "Release" .Release }}
{{- $context := deepCopy . }}
{{- $_ := set $context "component_code" "serviceaccount" }}
{{- $globals := .Values.global.mozcloud }}
{{- $labelParams := mergeOverwrite $chartMetadata (include "mozcloud.labelParams" . | fromYaml) }}
{{- $prefix := include "mozcloud.preview.prefix" . }}
{{- $serviceAccounts := default dict .Values.serviceAccounts }}
{{- $defaultServiceAccount := printf "%s%s" $prefix $globals.app_code }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $defaultServiceAccount }}
  labels:
    {{- $params := dict "context" (mergeOverwrite (deepCopy $context) $labelParams) }}
    {{- $labels := include "common.labels" $params | fromYaml }}
    {{- $labels.labels | toYaml | nindent 4 }}
  {{- $params = dict "type" "serviceAccount" }}
  {{- $annotations := include "common.annotations.argo" $params | fromYaml }}
  annotations:
    {{- $params = dict "gcpServiceAccount" (dict "name" (printf "gke-%s" $globals.env_code)) "globals" $globals }}
    {{- $gcpServiceAccount := include "mozcloud.serviceAccount.gcpServiceAccount" $params }}
    iam.gke.io/gcp-service-account: {{ $gcpServiceAccount }}
    {{- if $annotations }}
    {{- $annotations | toYaml | nindent 4 }}
    {{- end }}
{{- range $name, $config := $serviceAccounts }}
{{- $name = printf "%s%s" $prefix $name }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  labels:
    {{- $labels.labels | toYaml | nindent 4 }}
  {{- $params = dict "type" "serviceAccount" }}
  {{- $annotations := include "common.annotations.argo" $params | fromYaml }}
  {{- if or $annotations $config.gcpServiceAccount }}
  annotations:
    {{- if $config.gcpServiceAccount }}
    {{- $params = dict "gcpServiceAccount" $config.gcpServiceAccount "globals" $globals }}
    {{- $gcpServiceAccount := include "mozcloud.serviceAccount.gcpServiceAccount" $params }}
    iam.gke.io/gcp-service-account: {{ $gcpServiceAccount }}
    {{- end }}
    {{- if $annotations }}
    {{- $annotations | toYaml | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
