---
apiVersion: v2
name: mozcloud-workload-stateless-lib
description: helm chart for building stateless workloads
version: 0.2.1
type: library
dependencies:
  - name: mozcloud-workload-core-lib
    version: 0.5.1
    repository: file://../../mozcloud-workload-core/library
