{{- define "mozcloud-service-lib.service" -}}
{{- $config := merge (default dict (index . "config")) (include "mozcloud-service-lib.defaults.config" . | fromYaml) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mozcloud-service-lib.fullname" . }}
  labels:
    {{- include "mozcloud-service-lib.labels" . | nindent 4 }}
  {{- if (index . "annotations") }}
  annotations:
    {{ index . "annotations" | toYaml | nindent 4 }}
  {{- end }}
spec:
  type: {{ $config.type }}
  ports:
    {{- $config.ports | toYaml | nindent 4 }}
  selector:
    {{- include "mozcloud-service-lib.selectorLabels" . | nindent 4 }}
{{- end -}}
