{{- define "mozcloud-service-lib.service" -}}
{{- $config := merge (default dict .config) (include "mozcloud-service-lib.defaults.config" . | fromYaml).config }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mozcloud-service-lib.fullname" . }}
  {{- if .labels }}
  labels:
    {{- .labels | toYaml | nindent 4 }}
  {{- end }}
  {{- $annotation_params := dict "annotations" (default (dict) .annotations) "type" "service" }}
  {{- $annotations := include "mozcloud-labels-lib.annotations" (mergeOverwrite ($ | deepCopy) $annotation_params) | fromYaml }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  type: {{ $config.type }}
  ports:
    {{- $config.ports | toYaml | nindent 4 }}
  {{- if .selectorLabels }}
  selector:
    {{- .selectorLabels | toYaml | nindent 4 }}
  {{- end }}
{{- end -}}
