---
name: Run unit tests
on:
  pull_request: {}
  push:
    branches: [main]
    tags: ['*']

jobs:
  unit-tests:
    permissions:
      contents: write
      id-token: write

    runs-on:
      - ubuntu-latest

    steps:
      - name: Checkout Commit
        id: checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd #v5
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Helm
        uses: azure/setup-helm@29960d0f5f19214b88e1d9ba750a9914ab0f1a2f #v4.0.0

      - name: Setup Python
        uses: actions/setup-python@3542bca2639a428e1796aaa6a2ffef0c0f575566 #v3

      - name: Install uv
        uses: astral-sh/setup-uv@d0d8abe699bfb85fec6de9f7adb5ae17292296ff #v6 # zizmor: ignore[cache-poisoning]
        with:
          enable-cache: ${{ github.event_name != 'pull_request' }}

      - name: Install helm-docs
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release download --repo norwoodj/helm-docs v1.14.2 --pattern 'helm-docs_*_Linux_x86_64.tar.gz' --output /tmp/helm-docs.tar.gz
          tar -xzf /tmp/helm-docs.tar.gz --directory /usr/local/bin helm-docs
          chmod +x /usr/local/bin/helm-docs
          rm /tmp/helm-docs.tar.gz
        shell: bash

      - name: Install Helm unittest
        run: helm plugin install https://github.com/helm-unittest/helm-unittest.git --version=v1.0.3 --verify=false
        shell: bash

      - name: Update dependencies
        run: make update-dependencies
        shell: bash

      - name: Run pre-commit
        run: SKIP=helm-unittest uvx pre-commit run --show-diff-on-failure --color=always --all-files
        shell: bash

      - name: Run unit tests
        env:
          EVENT_NAME: ${{ github.event_name }}
          BASE_REF: ${{ github.base_ref }}
        run: |
          if [ "${EVENT_NAME}" == "pull_request" ]; then
            affected=$(uv run --directory ./scripts chartkit affected --base "origin/${BASE_REF}")
            if [ -n "$affected" ]; then
              uv run --directory ./scripts chartkit unittest $affected
            fi
          else
            make unit-tests
          fi
        shell: bash
